"""
Day-by-day plan: 23 Aug 2026 → 27 Dec 2026.

Each day has something to implement and something to publish. The publish
title is a blog post you actually write in this journal — not a tweet, a
short note that would still make sense in a year.
"""

from datetime import date, timedelta
from typing import Dict, List, Optional

START = date(2026, 8, 23)       # today — week 0
WEEK1 = date(2026, 8, 24)
END = date(2026, 12, 27)


def _d(day: date, week: int, project: str, do: str, publish: str,
       kind: str = "implement") -> Dict:
    return {
        "date": day.isoformat(),
        "week": week,
        "dow": day.strftime("%A"),
        "kind": kind,          # setup | implement | regression
        "project": project,
        "do": do,
        "publish": publish,
    }


def build() -> List[Dict]:
    days: List[Dict] = []

    # Week 0 — the remaining Sunday before the plan starts.
    days.append(_d(
        START, 0, "setup",
        "Install gcc, make, Python 3.11+, a venv per ML directory. "
        "Run `python3 progress.py --track core --checks` and keep the 0%. "
        "Write your track on the line in ROADMAP.md. Tomorrow is AWS, not a shell.",
        "The plan, the track I picked, AWS first, and a screenshot of 0%.",
        kind="setup"))

    # Order as of 23 Aug 2026: AWS → LLM → provenance → dist-train → DB → rest.
    # (week, mon_date, [(project, do, publish)] * 7  — Sun is usually regression)
    weeks = [
        (1, date(2026, 8, 24), [
            ("aws-from-scratch",
             "`iam.py` first. Everything else is gated by it. Do not open autograd.",
             "An explicit Deny is not order-dependent. I proved it."),
            ("aws-from-scratch",
             "`s3.py` then `sqs.py`. Checks start moving only after IAM is honest.",
             "A visibility timeout is how a queue does not double-deliver, until it does."),
            ("aws-from-scratch",
             "`dynamodb.py` then `lambda_svc.py`.",
             "The item I wrote that a later read could not see, and why that is legal."),
            ("aws-from-scratch",
             "`sns.py` → `kms.py` → `vpc.py`.",
             "A grant is not a key. A subnet is not a security group."),
            ("aws-from-scratch",
             "`capstone.py`, then start the bill: `pricing.py`.",
             "The two rounding rules AWS bills by, written down before I ran anything."),
            ("aws-from-scratch",
             "`billing.py` then `optimize.py`. Predict the DynamoDB crossover first.",
             "Provisioned vs on-demand: the crossover I wrote down, then the number I got."),
            ("week-1",
             "Sunday: 24/24 or name the gap. No autograd until the checker is green.",
             "What I can re-derive this Sunday that I could not last Sunday.",
             "regression"),
        ]),
        (2, date(2026, 8, 31), [
            ("autograd",
             "`tensor.py` — reverse mode, topological sort, `_unbroadcast`.",
             "A tensor used twice gets the SUM of both paths. I watched it."),
            ("autograd",
             "Stay in tensor.py. Every gradient matches central differences before nn.py.",
             "The op whose backward I had backwards, and how the check caught it."),
            ("autograd",
             "Still tensor.py if anything is red. Only then `nn.py`.",
             "What a residual is for, said without looking at the file."),
            ("autograd",
             "`optim.py` then `train.py`.",
             "The first loss that went down for a reason I can name."),
            ("autograd",
             "`generative.py` — the VAE. Reparameterisation is a path, not a sampler.",
             "The reparameterisation trick is a path for the gradient, not a sampler."),
            ("llm-from-scratch",
             "`tokenizer.py` — merges in rank order, not position order. Only if 10/10.",
             "Reversing merge rank changed the tokenisation. That is the test."),
            ("week-2",
             "Sunday: autograd 10/10. Do not start attention yet if tensor.py is still red.",
             "The gradient I can now re-derive that I could not on Monday.",
             "regression"),
        ]),
        (3, date(2026, 9, 7), [
            ("llm-from-scratch",
             "`attention.py` — causal mask and sqrt(d_k). Measure the entropy table.",
             "Unscaled d_k=256: the softmax is already one-hot before training."),
            ("llm-from-scratch",
             "`transformer.py`. Residuals you already own from autograd.",
             "What a residual is for, now in a stack of blocks."),
            ("llm-from-scratch",
             "`train.py` then `sample.py`. Then the mask ablation.",
             "Removing the causal mask made loss better and the model worthless."),
            ("llm-from-scratch",
             "`distill.py` — forward vs reverse KL vs JSD; on-policy vs off-policy.",
             "Mode-seeking vs mode-covering, as two numbers on the same pair."),
            ("llm-from-scratch",
             "OPD vs RL vs SFT; OPSD; Privilege Illusion.",
             "A falling distill loss that was the student copying the privilege tell."),
            ("llm-from-scratch",
             "Close the directory. 15/15. Do not open context-caching yet.",
             "The distillation claim I would defend without opening the file."),
            ("week-3",
             "Sunday: llm-from-scratch 15/15. No cache work this week.",
             "What I refused to start this week, and why that was the work.",
             "regression"),
        ]),
        (4, date(2026, 9, 14), [
            ("context-caching",
             "`tiny_transformer.py` then `kv_cache.py`. Cached and uncached must agree to zero.",
             "Bit-identical, not close. The cache that disagreed was a bug."),
            ("context-caching",
             "Stay on `kv_cache.py` until the identity holds. Then `prefix_cache.py`.",
             "A prefix that I did not recompute. The hit, as a number."),
            ("context-caching",
             "`radix_cache.py` then `paged_kv_cache.py`.",
             "Why only leaves of a radix cache are evictable."),
            ("context-caching",
             "`semantic_cache.py` then `cache_router.py` then `serving_demo.py`.",
             "The route I took that a hash cache would have missed."),
            ("inference-from-scratch",
             "Step 1 only if 16/16 is green: the GPU path for one prefill and one decode token.",
             "What actually happens on the GPU for every token — named kernels."),
            ("inference-from-scratch",
             "Step 2: naive server. Make it work. Two requests: `single_flight`.",
             "I watched the naive server fall apart, on purpose, and named the failure."),
            ("week-4",
             "Sunday: context-caching 16/16. Inference only as far as step 2. No vLLM.",
             "Cached vs uncached, still identical. What I would not have predicted Monday.",
             "regression"),
        ]),
        (5, date(2026, 9, 21), [
            ("inference-from-scratch",
             "Step 3: continuous batching. Measure TTFT, TPOT, throughput.",
             "The tokens static batching wasted, as a number, not a slogan."),
            ("inference-from-scratch",
             "Step 4: KV cache at runtime. Cached decode of 256 tokens is bandwidth-bound.",
             "Intensity vs the ridge. Decode crossed it. Prefill did not."),
            ("inference-from-scratch",
             "Step 5: scheduler — priority, backpressure, cancel, timeout.",
             "The request I refused, and why that is the product working."),
            ("inference-from-scratch",
             "Step 6: paged KV. Fork costs zero blocks until a write.",
             "I forked a sequence and the free-list did not shrink. Then I wrote."),
            ("inference-from-scratch",
             "Re-run steps 1–6. Name the knee if you already see it. Still no vLLM.",
             "Prefill vs decode, as two ledgers I can still draw."),
            ("inference-from-scratch",
             "Saturday: anything still red in steps 1–6. Do not start step 7.",
             "The step I thought would be easy and was not."),
            ("week-5",
             "Sunday: inference-from-scratch through step 6 green. I have not opened vllm-engine/.",
             "What I already know about serving without reading a vendor engine.",
             "regression"),
        ]),
        (6, date(2026, 9, 28), [
            ("inference-from-scratch",
             "Step 7: CUDA-graph-shaped replay, fusion, quant, one sync per step.",
             "Five kernels and five host syncs was the naive path. Now there is one."),
            ("inference-from-scratch",
             "Step 8: speculative decoding. Show a case that is slower.",
             "A bad draft of eight tokens lost to just decoding. The inequality."),
            ("inference-from-scratch",
             "Steps 9–10: observability, then load. Name the knee's reason.",
             "TTFT, ITL, KV used, queue time — on one request I can point at."),
            ("inference-from-scratch",
             "Step 11: NOW read vLLM, SGLang, TensorRT-LLM. Fill compare.py.",
             "Three engines, six decisions, and where mine already agreed."),
            ("inference-from-scratch",
             "Step 12: TP comm fraction, disagg transfer, offload, aware routing. 12/12.",
             "Random routing kept the prefix cache cold. Aware routing did not."),
            ("deploy-and-debug",
             "Capacity, percentiles, the 11 injected faults.",
             "The fault I diagnosed from metrics alone, and the one I guessed."),
            ("week-6",
             "Sunday: inference 12/12, deploy-and-debug moving. LLM work is closed.",
             "The serving claim I can now re-derive without opening a file.",
             "regression"),
        ]),
        (7, date(2026, 10, 5), [
            ("provenance-semirings",
             "The eight semirings. Check they obey the laws. Why ⊗ is pairwise union.",
             "Why is not lineage. I proved it on { {a} } ⊗ { {b} }."),
            ("provenance-semirings",
             "Sparse ℕ[X]. 2x, x², (x+y)(x+z).",
             "x ⊕ x is 2x. If I had used a set I would have got x."),
            ("provenance-semirings",
             "Specialize ac+bd by hand to bag, why, trust, tropical, security.",
             "max(0.9×0.8, 0.5×0.4) = 0.72. I wrote it down before specialize."),
            ("provenance-semirings",
             "Annotated RA. Join ⋈ project compact to ac+bd.",
             "Two join rows, one result. ⊕ on collision, or I still have two rows."),
            ("provenance-semirings",
             "THE PAYOFF: h(Q_How) = Q_K for every K. Do not hard-code ∪.",
             "The homomorphism held, or I built an annotation scheme. Which."),
            ("provenance-semirings",
             "Datalog. path(1,3) = e13 + e12 e23. How on a 2-cycle must raise.",
             "I refused to finish a cyclic path in ℕ[X]. Tropical gave 2."),
            ("week-7",
             "Sunday: 8/8. Lineage 4, bag 2, cost 7, from one polynomial.",
             "A set of source ids cannot answer how many and what it cost.",
             "regression"),
        ]),
        (8, date(2026, 10, 12), [
            ("scasp",
             "Unification. Chase. Occurs check rejects X = f(X).",
             "X = f(X) failed. Coinduction is not this; it lives in the call stack."),
            ("scasp",
             "Rename clauses. member/2 both answers. SLD on the even loop is None.",
             "member(X,[a,b]) bound both. p :- q. q :- p. hit max_steps."),
            ("scasp",
             "Duals. p(a) → not_p(X) :- neq(X,a). Conjuncts De Morgan.",
             "not p(X) is a call, not a failure. That is why it can bind."),
            ("scasp",
             "CoSLD: even loop succeeds, odd loop fails.",
             "p :- q. q :- p. is a success. p :- not p. is not an answer set."),
            ("scasp",
             "not p(a) fails, not p(b) succeeds. Then flies: opus yes, tweety no.",
             "tweety does not fly because penguin(tweety), not because I guessed."),
            ("scasp",
             "Justification tree. atoms_used is the lineage. Mark the even close.",
             "flies(opus) cites sparrow(opus) and does not cite penguin(tweety)."),
            ("week-8",
             "Sunday: 8/8. A query is a tree I can replay.",
             "The substitution is a projection of the tree, not the result.",
             "regression"),
        ]),
        (9, date(2026, 10, 19), [
            ("linc",
             "FOL AST. Ground ∀ over the domain. NNF pushes ¬.",
             "∀x (cat(x)→mammal(x)) over {fiona} is one implication. I wrote it."),
            ("linc",
             "GoldParser looks up fixtures. Unknown English is ok=False.",
             "The parse step is a function. There is no model in this directory."),
            ("linc",
             "Four faults: scope invert, drop ¬, arity drift, hallucinated const. Bins L1/L2/L3.",
             "Arity drift is L3, the paper's most common syntax error. I mapped it."),
            ("linc",
             "FaultyParser is seeded. Rate 0 is gold. Same seed, same corruption.",
             "The injector is a function of (gold, rate, seed). Replicable."),
            ("linc",
             "Prover: p1 True, p2 False, p3 Uncertain. p1 uses premises 0,1,2.",
             "False was derived (¬flies), not assumed. Uncertain invented nothing."),
            ("linc",
             "Sweep the error rate. Predict the table. Then trace.py through ℕ[X].",
             "accuracy(0)=1, and it did not rise. Lineage of p1 is {p0,p1,p2}."),
            ("week-9",
             "Sunday: 8/8. Same parse, same proof. The LLM is not consulted again.",
             "Traceable is the proof. Replicable is the prover. The parse is the risk.",
             "regression"),
        ]),
        (10, date(2026, 10, 26), [
            ("contextcite",
             "Partition, logit-probs, ablation. Why the logit and not the log-probability.",
             "Why the logit and not the log-probability, after seeing it saturate."),
            ("contextcite",
             "LASSO, then the full ContextCite path. 14/14 before SPADE.",
             "The sentence I ablated that actually moved the answer."),
            ("spade",
             "`deltas.py` then `taxonomy.py` then `candidates.py`.",
             "A prompt delta is a change I can name, not a vibe."),
            ("spade",
             "`selector.py` then `cite.py`. Cite through ContextCite. 8/8.",
             "The assertion I dropped because the SET's FFR, not the member's."),
            ("mars-sql",
             "`grounding.py` then `generation.py`. The typo becomes an observation.",
             "The typo became an observation, then a recovery."),
            ("mars-sql",
             "`validation.py` then `cite.py`. Self-consistency is the trap. 8/8.",
             "Self-consistency picked the popular wrong SQL. Validation did not."),
            ("week-10",
             "Sunday: 14/14, 8/8, 8/8. Tokens and columns, after derivations.",
             "ContextCite answers which words. ℕ[X] answers which proof. Both.",
             "regression"),
        ]),
        (11, date(2026, 11, 2), [
            ("distributed-training",
             "Data-parallel loader. Gradient accumulation you already wrote in autograd.",
             "The same accumulation, with a network in the middle."),
            ("distributed-training",
             "`template_trainer.py`. Close the directory.",
             "All-reduce vs the residual highway: two ways a sum saves you."),
            ("database-engine",
             "`pager.py` only. Slotted pages, free space, LRU buffer pool.",
             "A page that cannot find free space is a pager bug, not a B-tree bug."),
            ("database-engine",
             "Still the pager. Do not open btree.py.",
             "Why a B-tree on a shaky pager is a week you lose."),
            ("database-engine",
             "Pager tests green. Write the free-space arithmetic out by hand once.",
             "The slot directory, drawn, with a row that does not fit."),
            ("database-engine",
             "Saturday: pager only. If it is green, stop.",
             "What I refused to start this week, and why that was the work."),
            ("week-11",
             "Sunday: trainer runs; pager demo predicted then run. No B-tree.",
             "Distributed training closed. The pager I will bet a B-tree on.",
             "regression"),
        ]),
        (12, date(2026, 11, 9), [
            ("database-engine",
             "`btree.py`, then `wal.py`. WAL before MVCC.",
             "Durability is one writer and a disk. I wrote the log first."),
            ("database-engine",
             "Finish the WAL. Crash, recover, the page that must come back.",
             "The write I acknowledged and then replayed, on purpose."),
            ("database-engine",
             "`mvcc.py` — snapshot isolation, and the write skew it lets through.",
             "Write skew is not a bug in my code. It is the isolation level."),
            ("database-engine",
             "`sql.py` then start `executor.py`.",
             "A Volcano iterator is a next() that may call next()."),
            ("database-engine",
             "`executor.py` then `planner.py`.",
             "The plan I picked, and the one the cost model refused."),
            ("database-engine",
             "`database.py`. Aim at 18/18.",
             "The query that used every layer I built this week."),
            ("week-12",
             "Sunday: database-engine 18/18. One machine, ACID. Dynamo is next week.",
             "A page, a log, a snapshot. What I would now pick for a given crash.",
             "regression"),
        ]),
        (13, date(2026, 11, 16), [
            ("dynamo-paper",
             "Preference lists and vector clocks, paper open.",
             "A preference list that does not skip co-located virtual nodes stores 1 of 3."),
            ("dynamo-paper",
             "N/R/W, sloppy quorum, hinted handoff.",
             "The write I acknowledged and then lost, on purpose."),
            ("dynamo-paper",
             "Merkle sync, gossip, the cluster. 17/17 if you can.",
             "The number I predicted for the availability table, the number I got."),
            ("raft",
             "`log.py` and `election.py`. Read Figure 8 before replication.py.",
             "Why 'a majority has it' is the wrong commit rule."),
            ("raft",
             "`replication.py` and `cluster.py`. Safety after every op.",
             "A partition, a crash, and a commit that must not have happened."),
            ("raft",
             "Write the Raft-versus-Dynamo table in the journal before moving on.",
             "Same partition, opposite answers. The table."),
            ("week-13",
             "Sunday: 17/17 and 7/7 if you can, otherwise name the gap.",
             "One machine ACID, then the paper that throws it away, then the consensus it refuses.",
             "regression"),
        ]),
        (14, date(2026, 11, 23), [
            ("bash-from-scratch",
             "Tokenise a command line. `fork` / `exec` / `wait` for one program.",
             "What `wait` actually waits for, and why a shell without it looks fine."),
            ("bash-from-scratch",
             "Pipes, redirection, `Ctrl-C` without killing the shell, exit statuses.",
             "A pipeline is three processes and two pipes, not a metaphor."),
            ("http-server",
             "The accept loop: `socket`, `bind`, `listen`, `accept`. Nothing else.",
             "A file descriptor is how every later system in this repo begins."),
            ("http-server",
             "Parse the request line and headers. Reject junk without hanging.",
             "The request line is a tiny language. Parse it like one."),
            ("http-server",
             "Serve a real file with the right Content-Type. A real 404.",
             "A browser rendered my server. The 404 was a response, not a hang."),
            ("http-server",
             "Open a real browser against it. Fix whatever the browser shows.",
             "What the browser asked for that `curl` did not."),
            ("week-14",
             "Sunday: no new code. Re-run bash and the HTTP server.",
             "A shell and a server, after I already served tokens and proofs. What transferred.",
             "regression"),
        ]),
        (15, date(2026, 11, 30), [
            ("http-server",
             "Concurrency and keep-alive. Hold it under `ab -n 10000 -c 100`.",
             "What broke at 100 concurrent connections, and what I changed."),
            ("dns-server",
             "UDP sockets and the DNS wire format. Answer an A record.",
             "DNS is a 12-byte header and a lot of pointers. I answered one name."),
            ("cryptographic-library",
             "SHA-256: padding, message schedule, compression.",
             "Why the padding exists, by breaking a short message on purpose."),
            ("communication-protocols",
             "UART framing first. Then SPI.",
             "A start bit is a contract, not a voltage."),
            ("communication-protocols",
             "I2C, then CAN. The ACK is the lesson.",
             "Who owns the ACK, and what silence means on that bus."),
            ("toralizer",
             "SOCKS5 handshake in `network.c` / `socks.c`.",
             "A proxy is a conversation before it is a tunnel."),
            ("week-15",
             "Sunday regression. Re-run the HTTP server under load once more.",
             "The server still holds. What I would not have predicted on Monday.",
             "regression"),
        ]),
        (16, date(2026, 12, 7), [
            ("c-compiler",
             "`int main(){return 2+3;}` end to end. Lexer then parser.",
             "The first program my compiler ran, and the first one it refused."),
            ("c-compiler",
             "Semantic analysis and codegen. Linear-scan and a spill.",
             "I ran out of registers. The spill is the compiler becoming real."),
            ("compiler-and-vgpu",
             "ISA, assembler, scalar CPU. Get a program to halt with a value.",
             "One instruction set, two machines. The scalar one first."),
            ("compiler-and-vgpu",
             "SIMT warp, divergence, the barrier that deadlocks. 12/12 if you can.",
             "A mask stack is why warp divergence is not a mystery."),
            ("firewall-from-scratch",
             "Raw sockets, the first rule that drops something. Then toralizer.c.",
             "A packet is bytes until a parser says otherwise."),
            ("toralizer",
             "Finish `toralizer.c` if it is still open. Close the directory.",
             "What a SOCKS error looks like when the handshake lies."),
            ("week-16",
             "Sunday: compiler-and-vgpu should move. No new features.",
             "12 checks: how many are green, and which DESIGN DECISION I now defend.",
             "regression"),
        ]),
        (17, date(2026, 12, 14), [
            ("haskell-projects",
             "JSONParser.hs — parser combinators. Delete each `-- TODO`.",
             "A combinator is a function that returns a parser. That clicked today."),
            ("cuda-from-scratch",
             "Vector add. `nvidia-smi` today if the driver is not already honest.",
             "The first kernel's fraction of peak bandwidth, and the gap."),
            ("cuda-from-scratch",
             "Tiled matmul. Profile every kernel.",
             "Tiling moved the bound. I can say from where to where."),
            ("cuda-from-scratch",
             "Reduction, then a net. Delete each TODO as you satisfy it.",
             "A hand-written kernel vs cuBLAS: the factor, and why it is that factor."),
            ("ml-inference",
             "A forward pass and a latency harness. The baseline.",
             "The number I will spend the rest of the week beating, written down today."),
            ("ml-inference",
             "fp32 vs fp16 vs int8, latency AND accuracy. Find the knee.",
             "The accuracy I paid for the bytes I saved."),
            ("week-17",
             "Sunday: nvidia-smi works. CUDA bars move only if TODOs were deleted.",
             "The kernel I would still write by hand, and the one I would not.",
             "regression"),
        ]),
        (18, date(2026, 12, 21), [
            ("vllm-engine",
             "Read Phase 1. Sketch the block table. Re-read your paged_kv.py.",
             "The block table I had already built, next to theirs."),
            ("vllm-engine",
             "PagedAttention. Fork still costs zero additional blocks.",
             "A cache that changes the output is not a cache. I asserted it today."),
            ("world-models",
             "The VAE I already built in autograd/generative.py, revisited.",
             "A controller that never saw pixels, only z. What that costs."),
            ("diffusion-models",
             "Forward process first. Verify analytically against iterated noising.",
             "One-shot noising matched N steps. If it had not, I would have trained a lie."),
            ("web-scraping",
             "Five small wins: graphs, lineage, scrape, serve, log. Do not start anything heroic.",
             "The small directory I almost skipped and was glad I did not."),
            ("week-18",
             "Whatever is still red and small enough to finish.",
             "The Phase I thought would be easy and was not."),
            ("week-18",
             "Last day. Run every checker. Re-read the journal from 23 Aug. Close it.",
             "What I can re-derive today that I could not on 23 August.",
             "regression"),
        ]),
    ]

    for week_n, monday, slots in weeks:
        for i, slot in enumerate(slots):
            if len(slot) == 4:
                project, do, publish, kind = slot
            else:
                project, do, publish = slot
                kind = "implement"
            days.append(_d(monday + timedelta(days=i), week_n,
                           project, do, publish, kind))

    return days


def by_date() -> Dict[str, Dict]:
    return {row["date"]: row for row in build()}


def today_entry(today: Optional[date] = None) -> Optional[Dict]:
    today = today or date.today()
    return by_date().get(today.isoformat())


def week_of(today: Optional[date] = None) -> int:
    today = today or date.today()
    if today < WEEK1:
        return 0
    return min(18, (today - WEEK1).days // 7 + 1)
