-- Splitting Fields and Galois Extensions in Lean - Template
-- This file explores splitting fields, the cornerstone of Galois theory
-- Splitting fields are where polynomials "split" into linear factors

/-
LEARNING OBJECTIVES:
1. Understand splitting field definition and construction
2. Prove existence of splitting fields (constructive approach)
3. Establish uniqueness up to isomorphism
4. Define and work with normal extensions
5. Study separable polynomials and extensions
6. Understand perfect fields
7. Define Galois extensions (normal + separable + algebraic)
8. Compute concrete examples: ℚ(√2, √3), cyclotomic extensions
9. Prepare for Galois correspondence theorem

PREREQUISITES:
- Fields.lean (field axioms and properties)
- FieldExtensions.lean (towers, algebraic elements, degrees)
- Polynomials.lean (irreducible polynomials, roots, factorization)
-/

-- ============================================================================
-- PART 1: SPLITTING FIELD DEFINITION
-- ============================================================================

section SplittingFieldDefinition

variable {F : Type} [Field F]

-- A polynomial f splits over field E if it factors completely into linear terms
-- f = c · (X - r₁) · (X - r₂) · ... · (X - rₙ)
def Splits (E : Type) [Field E] [Algebra F E] (f : Polynomial F) : Prop :=
  ∃ (c : E) (roots : List E), 
    (∀ x, Polynomial.eval x (Polynomial.map (algebraMap F E) f) = 
          c * (roots.map (fun r => (x - r))).prod) ∧
    c ≠ 0

-- Alternative definition: f splits iff all irreducible factors are linear
def SplitsAlt (E : Type) [Field E] [Algebra F E] (f : Polynomial F) : Prop :=
  ∀ g : Polynomial E, 
    g ∣ (Polynomial.map (algebraMap F E) f) → 
    Irreducible g → 
    g.degree = 1

-- TODO 1.1: Prove the two definitions are equivalent
theorem splits_iff_alt (E : Type) [Field E] [Algebra F E] (f : Polynomial F) :
    Splits E f ↔ SplitsAlt E f :=
  sorry
  -- Hint: If splits, every irreducible factor divides a product of linears
  -- By irreducibility, must divide some linear factor, so is linear
  -- Conversely, if all irreducible factors linear, factor completely

-- A splitting field of f over F is a field extension E/F where:
-- 1. f splits completely over E
-- 2. E is generated by the roots of f (minimality condition)
structure SplittingField (f : Polynomial F) where
  carrier : Type
  field : Field carrier
  algebra : Algebra F carrier
  splits : Splits carrier f
  adjoin_roots : ∀ (K : Type) [Field K] [Algebra F K],
    Splits K f → 
    (∃ φ : carrier →ₐ[F] K, Function.Surjective φ) ∨
    (∀ r : carrier, (∃ g : Polynomial F, Polynomial.eval r (Polynomial.map (algebraMap F carrier) g) = 0 ∧ 
                                         g ∣ f) → 
     r ∈ Algebra.adjoin F {x : carrier | ∃ g, g ∣ f ∧ Polynomial.eval x (Polynomial.map (algebraMap F carrier) g) = 0})

-- TODO 1.2: Prove that f splits in its splitting field
theorem splits_in_splitting_field (f : Polynomial F) (E : SplittingField f) :
    Splits E.carrier f :=
  sorry
  -- Direct from definition

-- TODO 1.3: Prove splitting field is minimal
-- If f splits in E and K ⊆ E contains all roots, then K = E
theorem splitting_field_minimal (f : Polynomial F) (E : SplittingField f)
    (K : Type) [Field K] [Algebra F K] [Algebra K E.carrier] [IsScalarTower F K E.carrier]
    (h_splits : Splits K f)
    (h_roots : ∀ r : E.carrier, Polynomial.eval r (Polynomial.map (algebraMap F E.carrier) f) = 0 → 
               ∃ k : K, algebraMap K E.carrier k = r) :
    Function.Surjective (algebraMap K E.carrier) :=
  sorry
  -- Hint: E is generated by roots of f
  -- All roots are in K, so K maps onto E

-- TODO 1.4: Example - Splitting field of X² - 2 over ℚ is ℚ(√2)
example : ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
    Splits E (Polynomial.X ^ 2 - Polynomial.C 2) ∧
    FiniteDimensional.finrank ℚ E = 2 :=
  sorry
  -- E = ℚ(√2) = {a + b√2 | a, b ∈ ℚ}
  -- X² - 2 = (X - √2)(X + √2) over E
  -- [E : ℚ] = 2

end SplittingFieldDefinition

-- ============================================================================
-- PART 2: EXISTENCE OF SPLITTING FIELDS (Constructive Proof Sketch)
-- ============================================================================

section SplittingFieldExistence

variable {F : Type} [Field F]

-- Strategy: Induction on degree of polynomial
-- Base case: degree 0 or 1 - already splits
-- Inductive step: Adjoin one root, split further

-- TODO 2.1: Prove constant polynomials split over base field
theorem const_splits (c : F) : Splits F (Polynomial.C c) :=
  sorry
  -- Polynomial.C c has no roots (except if c = 0)
  -- Splits trivially as c itself

-- TODO 2.2: Prove linear polynomials split over base field
theorem linear_splits (a b : F) (ha : a ≠ 0) : 
    Splits F (Polynomial.C a * Polynomial.X + Polynomial.C b) :=
  sorry
  -- Linear already in form a(X - r) where r = -b/a
  -- Already has exactly one root

-- TODO 2.3: Adjoin one root of irreducible polynomial
-- If f is irreducible, F[X]/(f) is a field extension containing a root
def adjoin_root (f : Polynomial F) (hirr : Irreducible f) : Type :=
  sorry
  -- Quotient ring F[X]/(f) is a field (since f irreducible)
  -- Let r = X + (f) ∈ F[X]/(f)
  -- Then f(r) = 0 in F[X]/(f)

-- TODO 2.4: Prove adjoin_root is a field
instance adjoin_root_field (f : Polynomial F) (hirr : Irreducible f) : 
    Field (adjoin_root f hirr) :=
  sorry
  -- F[X]/(f) is a field since f irreducible
  -- Quotient by maximal ideal gives field

-- TODO 2.5: Prove f has a root in adjoin_root
theorem has_root_in_adjoin_root (f : Polynomial F) (hirr : Irreducible f) :
    ∃ r : adjoin_root f hirr, Polynomial.eval r (Polynomial.map (algebraMap F (adjoin_root f hirr)) f) = 0 :=
  sorry
  -- r = class of X in F[X]/(f) is a root by construction

-- TODO 2.6: Factor out a root and recurse
-- Key idea: If r is root of f, then f = (X - r) · g with deg(g) = deg(f) - 1
theorem factor_by_root {E : Type} [Field E] [Algebra F E] (f : Polynomial F) (r : E)
    (h : Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0) :
    ∃ g : Polynomial E, Polynomial.map (algebraMap F E) f = (Polynomial.X - Polynomial.C r) * g ∧
                        g.degree = f.degree - 1 :=
  sorry
  -- Polynomial remainder theorem: f(X) = (X - r)g(X) + f(r)
  -- Since f(r) = 0, we have f(X) = (X - r)g(X)
  -- Degree decreases by 1

-- TODO 2.7: Main existence theorem (by induction on degree)
theorem splitting_field_exists (f : Polynomial F) (hf : f ≠ 0) :
    ∃ E : Type, ∃ [Field E] [Algebra F E], Splits E f :=
  sorry
  -- Proof by strong induction on degree:
  -- Base: deg ≤ 1, already splits over F
  -- Step: Take irreducible factor g of f
  --       Adjoin root in E₁ = F[X]/(g)
  --       f factors as (X - r) · f' over E₁
  --       By IH, ∃ E splitting field of f' over E₁
  --       Then E is splitting field of f over F

-- TODO 2.8: Prove splitting field is finite dimensional
theorem splitting_field_finite_dimensional (f : Polynomial F) (hf : f ≠ 0)
    (E : Type) [Field E] [Algebra F E] (h : Splits E f) :
    FiniteDimensional F E :=
  sorry
  -- Construct as tower: F = E₀ ⊆ E₁ ⊆ ... ⊆ Eₙ = E
  -- Each Eᵢ₊₁ = Eᵢ(rᵢ) where rᵢ is root of some factor
  -- [Eᵢ₊₁ : Eᵢ] ≤ deg(f)
  -- So [E : F] ≤ (deg f)! by tower law

end SplittingFieldExistence

-- ============================================================================
-- PART 3: UNIQUENESS OF SPLITTING FIELDS (Up to Isomorphism)
-- ============================================================================

section SplittingFieldUniqueness

variable {F : Type} [Field F]

-- TODO 3.1: Extend field homomorphism to splitting field
-- Key lemma: If φ : F → F' and f splits over both E and E',
-- then φ extends to an isomorphism E ≅ E'
theorem extend_hom_to_splitting_field
    (f : Polynomial F)
    (E E' : Type) [Field E] [Field E'] [Algebra F E] [Algebra F E']
    (h_split : Splits E f) (h_split' : Splits E' f)
    (h_min : ∀ r : E, Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0 → 
             r ∈ Algebra.adjoin F {x : E | Polynomial.eval x (Polynomial.map (algebraMap F E) f) = 0})
    (h_min' : ∀ r : E', Polynomial.eval r (Polynomial.map (algebraMap F E') f) = 0 → 
              r ∈ Algebra.adjoin F {x : E' | Polynomial.eval x (Polynomial.map (algebraMap F E') f) = 0}) :
    ∃ φ : E ≃ₐ[F] E', True :=
  sorry
  -- Proof strategy:
  -- 1. Match roots: f has same roots in E and E' (as multisets)
  -- 2. Build isomorphism by matching roots
  -- 3. Use minimality: both fields generated by roots
  -- 4. φ determined by where it sends roots

-- TODO 3.2: Uniqueness up to isomorphism (main theorem)
theorem splitting_field_unique (f : Polynomial F) (hf : f ≠ 0)
    (E₁ E₂ : Type) [Field E₁] [Field E₂] [Algebra F E₁] [Algebra F E₂]
    (h₁ : Splits E₁ f) (h₂ : Splits E₂ f)
    (min₁ : ∀ r : E₁, Polynomial.eval r (Polynomial.map (algebraMap F E₁) f) = 0 → 
            r ∈ Algebra.adjoin F {x : E₁ | Polynomial.eval x (Polynomial.map (algebraMap F E₁) f) = 0})
    (min₂ : ∀ r : E₂, Polynomial.eval r (Polynomial.map (algebraMap F E₂) f) = 0 → 
            r ∈ Algebra.adjoin F {x : E₂ | Polynomial.eval x (Polynomial.map (algebraMap F E₂) f) = 0}) :
    Nonempty (E₁ ≃ₐ[F] E₂) :=
  sorry
  -- Apply extend_hom_to_splitting_field with identity on F
  -- Get F-algebra isomorphism E₁ ≃ₐ[F] E₂

-- TODO 3.3: Isomorphism preserves all field structure
-- This is automatic from the definition of ≃ₐ[F]
theorem splitting_field_iso_preserves_structure 
    (f : Polynomial F) (E₁ E₂ : Type) [Field E₁] [Field E₂] [Algebra F E₁] [Algebra F E₂]
    (φ : E₁ ≃ₐ[F] E₂) :
    (∀ a b, φ (a + b) = φ a + φ b) ∧
    (∀ a b, φ (a * b) = φ a * φ b) ∧
    (∀ a : F, φ (algebraMap F E₁ a) = algebraMap F E₂ a) :=
  sorry
  -- These follow from φ being an algebra isomorphism

end SplittingFieldUniqueness

-- ============================================================================
-- PART 4: NORMAL EXTENSIONS
-- ============================================================================

section NormalExtensions

variable {F : Type} [Field F]

-- An extension E/F is NORMAL if every irreducible polynomial over F 
-- that has one root in E splits completely over E
-- Intuition: "Closed under conjugates"
def IsNormal (E : Type) [Field E] [Algebra F E] : Prop :=
  ∀ f : Polynomial F, 
    Irreducible f →
    (∃ r : E, Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0) →
    Splits E f

-- TODO 4.1: Prove splitting fields are normal
theorem splitting_field_is_normal (f : Polynomial F) (E : Type) [Field E] [Algebra F E]
    (h_split : Splits E f)
    (h_min : ∀ r : E, Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0 → 
             r ∈ Algebra.adjoin F {x : E | Polynomial.eval x (Polynomial.map (algebraMap F E) f) = 0}) :
    IsNormal E :=
  sorry
  -- Let g be irreducible with root r in E
  -- Need to show g splits in E
  -- Since E is splitting field of f, r is algebraic over F
  -- g is minimal polynomial of r
  -- All conjugates of r are in E (contained in splitting field)
  -- So g splits in E

-- TODO 4.2: Prove normal extensions are splitting fields
theorem normal_iff_splitting_field [FiniteDimensional F E] (E : Type) [Field E] [Algebra F E] :
    IsNormal E ↔ 
    ∃ f : Polynomial F, (∀ r : E, Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0 → 
                         r ∈ Algebra.adjoin F {x : E | Polynomial.eval x (Polynomial.map (algebraMap F E) f) = 0}) ∧
                        Splits E f :=
  sorry
  -- Forward: If normal, take f = product of minimal polys of basis elements
  -- Backward: Already proved - splitting field is normal

-- TODO 4.3: Tower law for normal extensions
theorem normal_tower (K E : Type) [Field K] [Field E] [Algebra F K] [Algebra F E] [Algebra K E]
    [IsScalarTower F K E] (h_K : IsNormal K) (h_E : IsNormal E) :
    IsNormal E :=
  sorry
  -- If F ⊆ K ⊆ E with both extensions normal...
  -- Wait, this is not quite right!
  -- Correct statement: E/F normal iff E/K normal AND K/F normal? No!
  -- Actually: If E/F normal and K ⊆ E, then E/K NOT necessarily normal
  -- Example: ℚ ⊆ ℚ(∛2) ⊆ ℚ(∛2, ω∛2, ω²∛2)
  -- Last extension is normal over ℚ but ℚ(∛2) is not!

-- TODO 4.4: Normal closure
-- Every extension embeds in a normal extension (its normal closure)
-- The normal closure is the splitting field of all minimal polynomials
def NormalClosure (E : Type) [Field E] [Algebra F E] : Type :=
  sorry
  -- Take all minimal polynomials of elements in E
  -- Form their product
  -- Take splitting field of that polynomial

end NormalExtensions

-- ============================================================================
-- PART 5: SEPARABLE POLYNOMIALS
-- ============================================================================

section SeparablePolynomials

variable {F : Type} [Field F]

-- A polynomial is SEPARABLE if it has no repeated roots in its splitting field
-- Equivalently: gcd(f, f') = 1
def IsSeparable (f : Polynomial F) : Prop :=
  ∀ E : Type, ∀ [Field E] [Algebra F E],
    Splits E f →
    (∀ r : E, (Polynomial.map (algebraMap F E) f).Roots.count r ≤ 1)

-- TODO 5.1: Separable iff coprime with derivative
theorem separable_iff_coprime_derivative (f : Polynomial F) (hf : f ≠ 0) :
    IsSeparable f ↔ Polynomial.gcd f (Polynomial.derivative f) = 1 :=
  sorry
  -- Key fact: r is repeated root iff r is root of both f and f'
  -- f has repeated roots iff gcd(f, f') has degree ≥ 1
  -- So no repeated roots iff gcd(f, f') is constant

-- TODO 5.2: Irreducible polynomials in characteristic 0 are separable
theorem irreducible_separable_of_char_zero [CharZero F] (f : Polynomial F) 
    (hirr : Irreducible f) :
    IsSeparable f :=
  sorry
  -- If f irreducible and char(F) = 0, then f' ≠ 0 (degree drops by 1)
  -- gcd(f, f') divides f
  -- Since f irreducible, gcd is either 1 or f
  -- But gcd can't be f since deg(f') < deg(f)
  -- So gcd = 1, hence separable

-- TODO 5.3: Example of inseparable polynomial in characteristic p
-- Over 𝔽ₚ(t), the polynomial Xᵖ - t is irreducible but not separable
example {p : ℕ} [Fact (Nat.Prime p)] :
    ∃ F : Type, ∃ [Field F], ∃ f : Polynomial F,
      Irreducible f ∧ ¬IsSeparable f :=
  sorry
  -- Let F = 𝔽ₚ(t), f = Xᵖ - t
  -- In splitting field, Xᵖ - t = (X - r)ᵖ where rᵖ = t
  -- This is because (X - r)ᵖ = Xᵖ - rᵖ in characteristic p
  -- So r is a repeated root with multiplicity p

-- TODO 5.4: Separability is preserved under field homomorphisms
theorem separable_map (f : Polynomial F) (h : IsSeparable f)
    {E : Type} [Field E] (φ : F →+* E) :
    IsSeparable (f.map φ) :=
  sorry
  -- Roots of f.map φ correspond to roots of f
  -- Multiplicity is preserved under field homomorphisms

end SeparablePolynomials

-- ============================================================================
-- PART 6: SEPARABLE EXTENSIONS AND PERFECT FIELDS
-- ============================================================================

section SeparableExtensions

variable {F : Type} [Field F]

-- An element α is SEPARABLE over F if its minimal polynomial is separable
def IsSeparableElement (E : Type) [Field E] [Algebra F E] (α : E) : Prop :=
  ∃ f : Polynomial F, 
    (Polynomial.eval α (Polynomial.map (algebraMap F E) f) = 0) ∧
    (∀ g : Polynomial F, Polynomial.eval α (Polynomial.map (algebraMap F E) g) = 0 → f ∣ g) ∧
    IsSeparable f

-- An extension E/F is SEPARABLE if every element is separable
def IsSeparableExtension (E : Type) [Field E] [Algebra F E] : Prop :=
  ∀ α : E, IsSeparableElement E α

-- TODO 6.1: Separable extensions are closed under towers
theorem separable_tower (K E : Type) [Field K] [Field E] [Algebra F K] [Algebra F E] [Algebra K E]
    [IsScalarTower F K E] (h_K : IsSeparableExtension K) (h_E : IsSeparableExtension E) :
    IsSeparableExtension E :=
  sorry
  -- If K/F and E/K both separable, then E/F separable
  -- Minimal poly of α ∈ E over F divides product of minimal polys over K and of K-coeffs over F

-- A field F is PERFECT if every irreducible polynomial over F is separable
-- Equivalently: every finite extension is separable
class IsPerfectField (F : Type) [Field F] : Prop where
  all_irreducible_separable : ∀ f : Polynomial F, Irreducible f → IsSeparable f

-- TODO 6.2: Characteristic 0 fields are perfect
instance char_zero_perfect [CharZero F] : IsPerfectField F where
  all_irreducible_separable := sorry
  -- Already proved: irreducible in char 0 implies separable

-- TODO 6.3: Finite fields are perfect
instance finite_field_perfect [Fintype F] : IsPerfectField F where
  all_irreducible_separable := sorry
  -- Key: Frobenius map x ↦ xᵖ is an automorphism of finite fields
  -- If f not separable, then f = g(Xᵖ) for some g
  -- But Frobenius surjective, so f has a p-th root, contradicting irreducibility

-- TODO 6.4: Algebraic closure of perfect field is perfect
theorem perfect_algebraic_closure (F : Type) [Field F] [IsPerfectField F]
    (Falg : Type) [Field Falg] [Algebra F Falg] (h_alg : sorry) : -- algebraically closed
    IsPerfectField Falg :=
  sorry

end SeparableExtensions

-- ============================================================================
-- PART 7: GALOIS EXTENSIONS
-- ============================================================================

section GaloisExtensions

variable {F : Type} [Field F]

-- An extension E/F is GALOIS if it is:
-- 1. Normal (every irreducible with one root splits completely)
-- 2. Separable (every element has separable minimal polynomial)
-- 3. Algebraic (every element is a root of some polynomial)
def IsGalois (E : Type) [Field E] [Algebra F E] : Prop :=
  IsNormal E ∧ IsSeparableExtension E ∧ Algebra.IsAlgebraic F E

-- TODO 7.1: Galois extensions are splitting fields of separable polynomials
theorem galois_iff_splitting_field (E : Type) [Field E] [Algebra F E] [FiniteDimensional F E] :
    IsGalois E ↔
    ∃ f : Polynomial F, IsSeparable f ∧ Splits E f ∧
    (∀ r : E, Polynomial.eval r (Polynomial.map (algebraMap F E) f) = 0 → 
     r ∈ Algebra.adjoin F {x : E | Polynomial.eval x (Polynomial.map (algebraMap F E) f) = 0}) :=
  sorry
  -- Forward: Normal + separable means splitting field of separable poly
  -- Backward: Splitting field of separable poly is Galois

-- TODO 7.2: Finite extensions of perfect fields are Galois iff normal
theorem galois_iff_normal_over_perfect [IsPerfectField F] (E : Type) [Field E] [Algebra F E]
    [FiniteDimensional F E] :
    IsGalois E ↔ IsNormal E :=
  sorry
  -- Over perfect fields, every finite extension is separable
  -- So Galois = normal + separable = normal + automatic = normal

-- TODO 7.3: Galois closure
-- Every extension has a minimal Galois extension containing it
def GaloisClosure (E : Type) [Field E] [Algebra F E] : Type :=
  sorry
  -- Take normal closure (splitting field of all minimal polynomials)
  -- This is automatically separable if base field is perfect
  -- In general, also need to ensure separability

-- TODO 7.4: Quadratic extensions are Galois over characteristic ≠ 2
theorem quadratic_galois [Invertible (2 : F)] (E : Type) [Field E] [Algebra F E]
    (h : FiniteDimensional.finrank F E = 2) :
    IsGalois E :=
  sorry
  -- E = F(√d) for some d ∈ F
  -- Minimal poly is X² - d, which is separable if char ≠ 2
  -- X² - d splits over E as (X - √d)(X + √d)
  -- So E is splitting field of X² - d, hence Galois

end GaloisExtensions

-- ============================================================================
-- PART 8: CONCRETE EXAMPLES
-- ============================================================================

section Examples

-- TODO 8.1: ℚ(√2) is Galois over ℚ
example : ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
    IsGalois E ∧ FiniteDimensional.finrank ℚ E = 2 :=
  sorry
  -- E = ℚ(√2) = {a + b√2 | a, b ∈ ℚ}
  -- Splitting field of X² - 2
  -- X² - 2 is irreducible over ℚ (Eisenstein with p = 2)
  -- X² - 2 is separable (char 0)
  -- Splits as (X - √2)(X + √2) over E
  -- [E : ℚ] = 2

-- TODO 8.2: ℚ(√2, √3) is Galois over ℚ
example : ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
    IsGalois E ∧ FiniteDimensional.finrank ℚ E = 4 :=
  sorry
  -- E = ℚ(√2, √3) = {a + b√2 + c√3 + d√6 | a,b,c,d ∈ ℚ}
  -- Splitting field of (X² - 2)(X² - 3)
  -- Tower: ℚ ⊆ ℚ(√2) ⊆ ℚ(√2, √3)
  -- [ℚ(√2) : ℚ] = 2, [ℚ(√2, √3) : ℚ(√2)] = 2
  -- So [E : ℚ] = 4
  -- Galois group isomorphic to ℤ/2ℤ × ℤ/2ℤ

-- TODO 8.3: ℚ(∛2) is NOT Galois over ℚ
example : ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
    ¬IsGalois E ∧ FiniteDimensional.finrank ℚ E = 3 :=
  sorry
  -- E = ℚ(∛2) = {a + b∛2 + c∛4 | a,b,c ∈ ℚ}
  -- Minimal poly of ∛2 is X³ - 2, which is irreducible (Eisenstein)
  -- [E : ℚ] = 3
  -- But X³ - 2 does NOT split over E!
  -- Roots are ∛2, ω∛2, ω²∛2 where ω = e^(2πi/3)
  -- E only contains ∛2 (real root), not complex roots
  -- So E is not normal, hence not Galois

-- TODO 8.4: Cyclotomic extension ℚ(ζₙ) is Galois
-- ζₙ is primitive n-th root of unity, i.e., ζₙⁿ = 1
def cyclotomicPoly (n : ℕ) : Polynomial ℚ :=
  sorry  -- Φₙ(X) = ∏(X - ζ) over primitive n-th roots ζ

example (n : ℕ) (hn : n > 0) : 
    ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
      IsGalois E ∧ 
      FiniteDimensional.finrank ℚ E = (Nat.totient n) :=
  sorry
  -- E = ℚ(ζₙ) where ζₙ = e^(2πi/n)
  -- Splitting field of Xⁿ - 1
  -- Xⁿ - 1 splits completely in E as ∏(X - ζₙᵏ) for k = 0...n-1
  -- All n-th roots of unity lie in E
  -- Minimal polynomial is Φₙ(X) (cyclotomic polynomial)
  -- [E : ℚ] = φ(n) where φ is Euler's totient function
  -- Galois group Gal(ℚ(ζₙ)/ℚ) ≅ (ℤ/nℤ)ˣ (units mod n)

-- TODO 8.5: Splitting field of X⁴ - 2 over ℚ
example : ∃ E : Type, ∃ [Field E] [Algebra ℚ E],
    IsGalois E ∧ FiniteDimensional.finrank ℚ E = 8 :=
  sorry
  -- E = ℚ(∜2, i) where ∜2 = ⁴√2 (real fourth root)
  -- Roots of X⁴ - 2 are: ∜2, i∜2, -∜2, -i∜2
  -- Need to adjoin both ∜2 and i
  -- [ℚ(∜2) : ℚ] = 4, [ℚ(∜2, i) : ℚ(∜2)] = 2
  -- So [E : ℚ] = 8
  -- Galois group is dihedral group D₄ (order 8)

end Examples

/-
============================================================================
IMPLEMENTATION GUIDE SUMMARY
============================================================================

This file covers the theory of splitting fields and Galois extensions,
which are the foundation of Galois theory.

KEY DEFINITIONS:
1. Splits: A polynomial splits if it factors into linear terms
2. Splitting field: Minimal extension where polynomial splits
3. Normal extension: Irreducible polys with one root split completely
4. Separable polynomial: No repeated roots (coprime with derivative)
5. Separable extension: All elements have separable minimal polynomials
6. Perfect field: All irreducible polynomials are separable
7. Galois extension: Normal + separable + algebraic

MAIN THEOREMS:
1. EXISTENCE: Every polynomial has a splitting field (constructive proof)
   - Induction on degree
   - Adjoin one root at a time (quotient by irreducible)
   - Recurse on factored polynomial
   
2. UNIQUENESS: Splitting fields are unique up to isomorphism
   - Build isomorphism by matching roots
   - Use minimality condition
   
3. NORMAL ⇔ SPLITTING FIELD: For finite extensions
   - Normal extensions are exactly splitting fields
   
4. SEPARABLE: In characteristic 0, all irreducible polynomials separable
   - Use gcd(f, f') criterion
   - In characteristic p, can have inseparable polynomials
   
5. GALOIS: E/F Galois ⇔ E is splitting field of separable polynomial

PROOF TECHNIQUES:
- Induction on polynomial degree (existence)
- Matching roots via homomorphisms (uniqueness)
- Tower law for field extensions
- Derivative criterion for separability
- Characteristic-dependent arguments

CONCRETE EXAMPLES:
- ℚ(√2): Splitting field of X² - 2, [E:ℚ] = 2, Galois
- ℚ(√2, √3): Splitting field of (X²-2)(X²-3), [E:ℚ] = 4, Galois
- ℚ(∛2): Degree 3, but NOT Galois (not normal - missing complex roots)
- ℚ(ζₙ): Cyclotomic extensions, [E:ℚ] = φ(n), Galois

CONNECTION TO GALOIS THEORY:
- Splitting fields are the fields we study in Galois theory
- Galois extensions have rich automorphism groups (Galois groups)
- Normal subgroups ↔ Normal extensions (Galois correspondence)
- This file prepares for the Fundamental Theorem of Galois Theory

NEXT STEPS:
After SplittingFields.lean, move to GaloisTheory.lean
- Define Galois group Gal(E/F)
- Prove Fundamental Theorem (bijection: subgroups ↔ intermediate fields)
- Study solvability by radicals
- Applications to classical problems (compass and straightedge, etc.)
-/
